// Code generated by MockGen. DO NOT EDIT.
// Source: router.go
//
// Generated by this command:
//
//	mockgen -source=router.go -destination=mocks/router.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockBillController is a mock of BillController interface.
type MockBillController struct {
	ctrl     *gomock.Controller
	recorder *MockBillControllerMockRecorder
	isgomock struct{}
}

// MockBillControllerMockRecorder is the mock recorder for MockBillController.
type MockBillControllerMockRecorder struct {
	mock *MockBillController
}

// NewMockBillController creates a new mock instance.
func NewMockBillController(ctrl *gomock.Controller) *MockBillController {
	mock := &MockBillController{ctrl: ctrl}
	mock.recorder = &MockBillControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillController) EXPECT() *MockBillControllerMockRecorder {
	return m.recorder
}

// ReplaceShareSet mocks base method.
func (m *MockBillController) ReplaceShareSet(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReplaceShareSet", arg0)
}

// ReplaceShareSet indicates an expected call of ReplaceShareSet.
func (mr *MockBillControllerMockRecorder) ReplaceShareSet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceShareSet", reflect.TypeOf((*MockBillController)(nil).ReplaceShareSet), arg0)
}

// ShareSet mocks base method.
func (m *MockBillController) ShareSet(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShareSet", arg0)
}

// ShareSet indicates an expected call of ShareSet.
func (mr *MockBillControllerMockRecorder) ShareSet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShareSet", reflect.TypeOf((*MockBillController)(nil).ShareSet), arg0)
}

// MockPersonController is a mock of PersonController interface.
type MockPersonController struct {
	ctrl     *gomock.Controller
	recorder *MockPersonControllerMockRecorder
	isgomock struct{}
}

// MockPersonControllerMockRecorder is the mock recorder for MockPersonController.
type MockPersonControllerMockRecorder struct {
	mock *MockPersonController
}

// NewMockPersonController creates a new mock instance.
func NewMockPersonController(ctrl *gomock.Controller) *MockPersonController {
	mock := &MockPersonController{ctrl: ctrl}
	mock.recorder = &MockPersonControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonController) EXPECT() *MockPersonControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPersonController) Create(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", arg0)
}

// Create indicates an expected call of Create.
func (mr *MockPersonControllerMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPersonController)(nil).Create), arg0)
}

// List mocks base method.
func (m *MockPersonController) List(arg0 *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", arg0)
}

// List indicates an expected call of List.
func (mr *MockPersonControllerMockRecorder) List(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPersonController)(nil).List), arg0)
}
