// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	bill "github.com/nachoconques0/splitter_svc/backend/internal/entity/bill"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ExistingPeople mocks base method.
func (m *MockRepository) ExistingPeople(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistingPeople", ctx, ids)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistingPeople indicates an expected call of ExistingPeople.
func (mr *MockRepositoryMockRecorder) ExistingPeople(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistingPeople", reflect.TypeOf((*MockRepository)(nil).ExistingPeople), ctx, ids)
}

// FindByID mocks base method.
func (m *MockRepository) FindByID(ctx context.Context, id uuid.UUID) (bill.Bill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(bill.Bill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository)(nil).FindByID), ctx, id)
}

// ReplaceShareSet mocks base method.
func (m *MockRepository) ReplaceShareSet(ctx context.Context, id uuid.UUID, expectedVersion int64, shares bill.ShareSet) (bill.Bill, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceShareSet", ctx, id, expectedVersion, shares)
	ret0, _ := ret[0].(bill.Bill)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceShareSet indicates an expected call of ReplaceShareSet.
func (mr *MockRepositoryMockRecorder) ReplaceShareSet(ctx, id, expectedVersion, shares any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceShareSet", reflect.TypeOf((*MockRepository)(nil).ReplaceShareSet), ctx, id, expectedVersion, shares)
}
